project:
  type: website

website:
  title: "Richard Decal"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/crypdick
      - icon: twitter
        href: https://twitter.com/bae_theorem
      - icon: linkedin
        href: https://linkedin.com/in/richarddecal
format:
  html:
    theme: cosmo
    css: styles.css



