---
title: On the Democratic Party Enthusiasm Gap
subtitle: An explainer for my overseas colleagues
categories: [politics]
date: "2024-11-06"
draft: true
---

I'm getting messages from overseas folks who can't wrap their minds around how Trump won a second term today. As someone living in the USA, I'm not surprised. It would take a book to explain the dynamics to outsiders, so in this post I am focusing on a crucial but less visible facet: the Democratic Party's lack of voter excitement.

### The enthusiasm gap

One glaring difference between Trump supporters and Democratic voters is the enthusiasm gap. Trump stickers, flags, and rallies are everywhere, and Trump supporters are vocal and passionate. In contrast, in the past three elections it has been hard to find any visible support for Harris, Biden, or Clinton. During a 27-state road trip before the 2016 election, I saw more Bernie Sanders stickers than Hillary Clinton ones, even in Democratic strongholds like Seattle.

Lack of excitement means fewer volunteers canvassing or displaying stickers. People are social creatures by nature and notice this disparity, and I think this is especially true for low-information voters.

### So why is the DNC so unexciting?

With Congress [polling less favorably than cockroaches](https://www.cbsnews.com/miami/news/poll-congress-less-popular-than-cockroaches-root-canals-and-nickelback/), you would think that the DNC would embrace new and popular candidates to join the ranks.

Having been politically active in my 20s, I've experienced first-hand why the Democratic Party is often dubbed the "graveyard of progressive movements." Millions of energized voters [supported progressive candidates](https://www.politico.com/news/2020/01/02/bernie-sanders-fundraising-millions-092446), only for the party elite to [tilt the scales](https://www.youtube.com/watch?v=u4IsqmMqCEo) [against them](https://www.realclearpolitics.com/video/2016/05/15/chaos_at_nevada_democratic_convention_dnc_leaders_flee_building_as_sanders_supporters_demand_recount.html).

While it's true that these junior candidates were unlikely to win even without these interventions, that's not the point. Repeatedly undermining grassroots movements election after election has the effect of dampening enthusiasm for your party and making your base apathetic. Of course, I'd rather vote for the graveyard of progressive movements than the graveyard of American Democracy, but in contrast, the Republican Party has harnessed its base's energy effectively.

You would also think that they would be more respondent to the will of the people in order to gain popularity. Yet, their voting record has little correlation with the popular will while being highly correlated with [wealthy interests](https://youtu.be/PJy8vTu66tE?si=QvvF80Lk4-P3wan8&t=514).


### Cowardly Defenders

The Democratic Party brands itself as a defender of democracy but have not had the backbone to act decisively against illegal acts. And yet, time and time again they failed to politicians accountable for the hundreds of well-documented crimes committed by the Trump administration and the Republican Party more broadly.

You would also expect that as Republicans repeatedly (and hypocritically) attacking the DNC as corrupt, that they would try to maintain the highest ethical standards. And yet, many Democrats use [insider information to make millions](https://theintercept.com/2022/09/30/house-stocks-trade-ban-fail/). 

Given that the main selling point of voting for the Democrats is that they are the last defense against fascism, their inaction makes this selling point weaker. As system theorists like to say, ["the purpose of the system is what it does"](https://en.wikipedia.org/wiki/The_purpose_of_a_system_is_what_it_does). The DNC can't claim to be something that it constantly fails to do.

### Media Complicity

A formative experience for me in the early 2000s was watching The Daily Show. One of Jon Stewart's recurring bits was showcasing montages of TV personalities echoing identical talking points within hours, which made it obvious that it was an astroturfed consensus. It exposed the legacy media as carefully coordinated corporate messaging, a theatrical performance packaged as honest debates and analysis.

With Republicans popularizing the "fake news" narrative, you'd hope that the legacy media would tighten the ship and strive for impartiality, authenticity, and journalistic integrity. Instead, it often appeared to assist Democratic elites in discrediting candidates as [Russian agents](https://youtu.be/_El9riy9Zjw?si=e1oQc_IRjafvKoRW&t=2503) or ignoring [popular rallies](https://pressbooks.bccampus.ca/prcasestudies/chapter/case-study-14/). While not as overtly biased as Fox News, this contributes to the perception that major news outlets serves to [manufacture consent](https://en.wikipedia.org/wiki/Manufacturing_Consent), which drove audiences to alternative sources.

Ideally, folks would've switched to high-quality independent media, but instead they flocked to podcasters, which, similar to talk shows, are often a place to get a [softball interview](https://www.youtube.com/watch?v=blqIZGXWUpU) where they can spread an unchallenged narrative.

With the legacy media's influence waning, you'd expect the Democratic candidates to meet voters where they are at and go on popular podcasts. Instead, they avoided them-- a major unforced error in my opinion. Meanwhile, Trump and his surrogates were doing the podcast circuit, with interviews reaching millions of viewers. The podcast hosts were more than happy to give them softball interviews, as it was a viewership bonanza.

In fairness, I am told that the Harris campaign did a great job of creating short-form social media content (no opinion here as I quit social media and I also use ad blockers). But I believe that people are more likely to update their beliefs from a 2-hour conversation than these short clips.

### Conclusion

There are of course a lot of criticisms to be said about the Trump faction. Ultimately, it's the DNC's responsibility to win the election, and no amount of finger pointing is going to change that. The party needs to bridge the enthusiasm gap, or they will keep losing to right wing populists. I think this is possible by embracing progressive candidates, ensuring fair media representation, and holding itself to stricter ethical standards.